create table addresses (
    id bigint generated by default as identity,
    city varchar(255),
    country varchar(255),
    housenumber varchar(255),
    latitude double,
    longitude double,
    street varchar(255),
    type varchar(255),
    zipcode varchar(255),
    contact_id bigint,
    primary key (id)
);

alter table addresses 
    add constraint FK_snbmj50f2xwyihra3scm6h38n 
    foreign key (contact_id) 
    references contacts;