create table musictracks (
        id bigint generated by default as identity,
        album varchar(255),
        artist varchar(255),
        filepath varchar(255),
        genre varchar(255),
        length bigint not null,
        title varchar(255),
        trackNumber bigint not null,
        pubYear varchar(255),
        primary key (id)
);